package("bmk")
set_kind("addon")
set_description("Build rules for Bethesda modding")
set_license("MIT")
add_urls("https://github.com/gabriel-andreescu/BethesdaModKit.git")
add_versions("0.3.1", "v0.3.1")
add_versions("0.3.0", "v0.3.0")
add_versions("0.2.0", "v0.2.0")
add_versions("0.1.0", "v0.1.0")
