package("bmk")
set_kind("library", { headeronly = true })
set_description("Native helpers for Bethesda modding")
set_license("MIT")
set_sourcedir(path.join(os.scriptdir(), "../../.."))
add_versions("0.5.0", "local")
add_versions("0.4.0", "local")
add_versions("0.3.1", "local")
add_versions("0.3.0", "local")
add_versions("0.2.0", "local")
add_versions("0.1.0", "local")
on_install(function(package)
    os.cp("native/include/*", package:installdir("include"))
    os.cp("LICENSE", package:installdir("share"))
end)
