package("bmk")
set_kind("library", { headeronly = true })
set_description("Native helpers for Bethesda modding")
set_license("MIT")
set_sourcedir(path.join(os.scriptdir(), "../../.."))
on_install(function(package)
    os.cp("native/include/*", package:installdir("include"))
    os.cp("LICENSE", package:installdir("share"))
end)
