package("skyrim-papyrus-sources")
set_kind("library", { headeronly = true })
set_homepage("https://github.com/BellCubeDev/papyrus-index")
set_description("Vanilla Skyrim Papyrus interfaces indexed from Skyrim 1.6.1170")
add_includedirs("include")
add_urls("https://github.com/BellCubeDev/papyrus-index/archive/ec822650d44885707c01e90eeb569551f0ab8ddb.tar.gz")
add_versions("ec822650", "a6988fb829b85ae37a69c96a2d3af206ec5126d7f30b06519962febade55d7db")
on_install(function(package)
    local share = package:installdir("share/skyrim-papyrus-sources")
    os.cp("data/SkyrimSE/vanilla/*.psc", package:installdir("include"))
    os.cp("LICENSE.md", path.join(share, "LICENSE.md"))
    os.cp("data/README.md", path.join(share, "DATA-README.md"))
    os.cp("data/SkyrimSE/vanilla/meta.yaml", path.join(share, "vanilla-meta.yaml"))
end)
