set_project("BMKNativeTests")
set_languages("c++23")
set_defaultmode("releasedbg")
add_rules("mode.releasedbg")
add_rules("plugin.compile_commands.autoupdate", { outputdir = ".", lsp = "clangd" })
add_repositories("bmk " .. path.join(os.scriptdir(), "../.."))
add_requires("catch2 3.8.1", "clib-util 1.5.0")
add_requires("spdlog 1.16.0", { configs = { header_only = false, wchar = true, std_format = true } })

target("InspectionTaskTests", function()
    set_kind("binary")
    add_rules("platform.windows.subsystem")
    set_values("windows.subsystem", "console")
    add_files("skyrim/InspectionTaskTests.cpp")
    add_includedirs("../../native/include")
    add_packages("catch2")
    add_tests("inspection")
    after_config(function(target)
        if target:has_tool("cxx", "cl") then
            target:add("symbols", "embed")
        end
    end)
end)

target("SettingsTests", function()
    set_kind("binary")
    add_rules("platform.windows.subsystem")
    set_values("windows.subsystem", "console")
    add_files("SettingsTests.cpp")
    add_includedirs("../../native/include")
    add_packages("catch2", { components = { "main", "lib" } })
    add_packages("clib-util", "spdlog")
    add_tests("settings")
    after_config(function(target)
        if target:has_tool("cxx", "cl") then
            target:add("symbols", "embed")
        end
    end)
end)
